### ISSUE TITLE
"extends" component does not work

### ISSUE THREAD

**Issue by herrbischoff** [dreerr/TemplateEngineJade#1]
## Issue

Contrary to the Jade documentation and jade-php implementation, `extends` does not work. `include` does work however.
## Test Case

``` jade
//- layout.jade
doctype html
html
  head
    block title
      title Default title
  body
    block content
```

``` jade
//- index.jade
extends ./layout.jade

block title
  title Article Title

block content
  h1 My Article
```

This should result in

``` html
<!doctype html>
<html>
  <head>
    <title>Article Title</title>
  </head>
  <body>
    <h1>My Article</h1>
  </body>
</html>
```

It however outputs nothing.
## Environment

ProcessWire 2.7.2 Master/Stable
PHP 7.0.3
Apache/2.4.18 (Unix)

**Comment by dreerr** [comment]
Instead of `extends ./index.jade` try `extends ./index` like in the jade-php example folder
This is because the file extension is given at init…

**Comment by herrbischoff** [comment]
Thanks, this indeed works as expected.
