### ISSUE TITLE
Can't include .pug files

### ISSUE THREAD

**Issue by Sega01** [dreerr/TemplateEngineJade#2]
Hi, 

I'm trying to include a header and footer file to my index-template.

In the index.pug i tried to "include head.pug" and i got just the plain code as text from the file.
Including in the php files didn't worked aswell.

Any ideas how i can do that?

**Comment by dreerr** [comment]
Did you set the extension from jade to pug? I have a more recent version with the updated Pug lib, will up it asap.

**Comment by Sega01** [comment]
Yes, i changed the extension to pug and right now i working with "extends" and block elements for now

**Comment by dreerr** [comment]
Please use https://github.com/dreerr/TemplateEnginePug instead. It uses the updated lib and works fine with pug files.
