### ISSUE TITLE
If-statement issues 

### ISSUE THREAD

**Issue by Sega01** [dreerr/TemplateEngineJade#3]
Hi, 

its again me.
I thought i open a new thread, because i have a new problem: I try to work with if-statements in Jade/Pug but somehow he don't accept it.

For example, if i write 

`if nav_page->id == current`

i get the following  error: 

`Error: Exception: JadePHP do not understand nav_page->id == current (in /Applications/MAMP/htdocs/processwire-master/site/modules/TemplateEngineJade/TemplateEngineJade.module line 113)

#0 /Applications/MAMP/htdocs/processwire-master/site/modules/TemplateEngineFactory/TemplateEngineFactory.module.php(119): TemplateEngineJade->render()
#1 /Applications/MAMP/htdocs/processwire-master/wire/core/WireHooks.php(629): TemplateEngineFactory->hookRender(Object(ProcessWire\HookEvent))
#2 /Applications/MAMP/htdocs/processwire-master/wire/core/Wire.php(399): ProcessWire\WireHooks->runHooks(Object(ProcessWire\Page), 'render', Array)
#3 /Applications/MAMP/htdocs/processwire-master/wire/modules/Process/ProcessPageView.module(205): ProcessWire\Wire->__call('render', Array)
#4 /Applications/MAMP/htdocs/processwire-master/wire/modules/Process/ProcessPageView.module(205): ProcessWire\Page->render()
#5 [internal function]: ProcessWire\ProcessPageView->___execute(true)
#6 /Ap
`

Is there a fix for it?

**Comment by dreerr** [comment]
Try using $ sign?

**Comment by dreerr** [comment]
Statements like `if $page->parent->template == $page->template` work for me!
